# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MTFmOTk1MmU5ZjJhZmNjN2U4MTIxZjg1ZGFkZjhhZDIxYWIxYWIyMmJlNGQxZTJkZWQ5NTMwNjQ0MGI2YjY3MjM4MjhkZDJlYzZmMTEwZDIwZDRlNWEwNGZiMzIxNTdlOGE5NzAxYzhjZTNkOTY3NzQwM2RkMTJlZGJmNTFjMjk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
